name: Android Build And Deployment

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      - name: Decode Service Account Key JSON File
        run: gpg --batch --yes --decrypt --passphrase "${{ secrets.KEYSTORE_PASSPHRASE }}" --output ./android/app/holidaily-fastlane.json ./android/app/holidaily-fastlane.json.gpg 
      - name: Decode Keystore
        run: gpg -d --passphrase "${{ secrets.KEYSTORE_PASSPHRASE }}" --batch android/app/HolidailyProd.keystore.gpg > android/app/HolidailyProd.keystore
      - name: Build & deploy Android release
        run:  printf "HOLIDAILY_UPLOAD_STORE_PASSWORD=${{ secrets.HOLIDAILY_UPLOAD_STORE_PASSWORD }}\nHOLIDAILY_UPLOAD_KEY_PASSWORD=${{ secrets.HOLIDAILY_UPLOAD_KEY_PASSWORD }}" >> android/gradle.properties && bundle exec fastlane android beta
        env:
          ANDROID_PACKAGE_NAME: com.holidaily
          ANDROID_JSON_KEY_FILE: android/app/holidaily-fastlane.json
          HOLIDAILY_UPLOAD_STORE_FILE: HolidailyProd.keystore
          HOLIDAILY_UPLOAD_KEY_ALIAS: HolidailyProdKey
          HOLIDAILY_UPLOAD_STORE_PASSWORD: ${{ secrets.HOLIDAILY_UPLOAD_STORE_PASSWORD }}
          HOLIDAILY_UPLOAD_KEY_PASSWORD: ${{ secrets.HOLIDAILY_UPLOAD_KEY_PASSWORD }}
