name: Android Build And Deployment

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      - name: Decode Service Account Key JSON File
        run: echo $GPLAY_SERVICE_ACCOUNT_KEY | base64 -di > android/app/holidaily-fastlane.json
        env:
          GPLAY_SERVICE_ACCOUNT_KEY: ${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY }}
      - name: Decode Keystore
        run: echo $KEYSTORE_GPD > HolidailyProd.keystore.asc && gpg -d -passphrase "${{ secrets.KEYSTORE_PASSPHRASE }}" --batch HolidailyProd.keystore.asc > android/app/HolidailyProd.keystore
        env:
          KEYSTORE_GPD: ${{ secrets.KEYSTORE_GPD }}
      - name: Build & deploy Android release
        run: bundle exec fastlane android beta
        env:
          ANDROID_JSON_KEY_FILE: android/app/holidaily-fastlane.json
